version: "3.8"

services:
  postgresql:
    image: postgres:15.3-alpine # images repo: https://hub.docker.com/_/postgres
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      #      POSTGRES_USER: postgres # default user - postgres
      POSTGRES_PASSWORD: postgres # default password - postgres
#      POSTGRES_DB: postgres # If it is not specified, then the value of POSTGRES_USER will be used.
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
