version: "3.8"

services:
  # Docs: https://www.keycloak.org/server/containers
  # If you have problems with realm import: https://documentation.cloud-iam.com/en/article/error-creating-xxxxx-javalangruntimeexception-script-upload-is-disabled-lkqprx/

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    command: start-dev --import-realm
    volumes:
      - ./imports:/opt/keycloak/data/import
#      - keycloak-data:/opt/keycloak/data
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8081:8080"

#volumes:
#  keycloak-data: